# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddfc520a4f8a0b1a69506a0d85f9bc41595a3f9796b83916667b6168a1b12273c950ab0fcb8583160ae66af6c1bbd1c8902c378a7ad12ea46dd7c5780b32f2df

test:
  secret_key_base: 4e740e1f92c95ae60538237da88b9f5e0ac0a996e050dfec410580747d144e13748a191c13ff586aeba40dbbf34eaa0fe7f7af523f637acaecda5a4b72c81b05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
